version: '3.8'

services:
  app:
    image: 'docker-springboot-pg-upc:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/techelp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "80:8080"

  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DB=techelp
    ports:
      - "3306:3306"